var courses = 
    [
        {
            "id": 1,
            "image": "https://img-a.udemycdn.com/course/240x135/959700_8bd2_11.jpg",
            "title": "The Complete React Native + Hooks Course [2020 Edition]",
            "author": "Stephen Grider",
            "rating": 4.6,
            "hours": 38,
            "price": 14.99,
        },
        {
            "id": 2,
            "image": "https://img-a.udemycdn.com/course/240x135/1286908_1773_5.jpg",
            "title": "The Complete React Developer Course (w/ Hooks and Redux)",
            "author": "Andrew Mead",
            "rating": 4.7,
            "hours": 39,
            "price": 9.99,
        },
        {
            "id": 3,
            "image": "https://img-a.udemycdn.com/course/240x135/2018828_41a9_3.jpg",
            "title": "React Tutorial and Projects Course",
            "author": "Jhon Smilga",
            "rating": 4.6,
            "hours": 33,
            "price": 9.99,
        },
        {
            "id": 4,
            "image": "https://img-a.udemycdn.com/course/240x135/1411694_0862.jpg",
            "title": "The complete React Fullstack course ( 2nd edition )",
            "author": "Coding Revolution",
            "rating": 4.7,
            "hours": 29,
            "price": 9.99,
        },
        {
            "id": 5,
            "image": "https://img-a.udemycdn.com/course/240x135/822444_a6db.jpg",
            "title": "Python and Django Full Stack Web Developer Bootcamp",
            "author": "Jose Portilla",
            "rating": 4.5,
            "hours": 32,
            "price": 9.99,
        },
        {
            "id": 6,
            "image": "https://img-a.udemycdn.com/course/240x135/2593518_856b.jpg",
            "title": " Django & Python: complete BUNDLE + Django real project 2020",
            "author": " arash Shahvar",
            "rating": 4.5,
            "hours": 56,
            "price": 9.99,
        },
        {
            "id": 7,
            "image": "https://img-a.udemycdn.com/course/240x135/1396598_5622.jpg",
            "title": "Python eCommerce | Build a Django eCommerce Web Application",
            "author": "Justin Mitchel",
            "rating": 4.4,
            "hours": 33,
            "price": 10.99,
        },
        {
            "id": 8,
            "image": "https://img-a.udemycdn.com/course/240x135/1094964_35b4_4.jpg",
            "title": "Build a Backend REST API with Python & Django - Beginner",
            "author": "Mark Winterbottom",
            "rating": 4.6,
            "hours":  22,
            "price": 9.99,
        },
        {
            "id": 9,
            "image": "https://img-a.udemycdn.com/course/240x135/2701028_ef70_2.jpg",
            "title": "Django 3 - Full Stack Websites with Python Web Development",
            "author": "Nick Walter",
            "rating": 4.6,
            "hours": 18,
            "price": 18.99,
        },
        {
            "id": 10,
            "image": "https://img-a.udemycdn.com/course/240x135/2306906_87e4.jpg",
            "title": "React & Django Full Stack: web app, backend API, mobile apps",
            "author": "Krystian Czekalski",
            "rating":4.2,
            "hours": 12,
            "price": 9.99,
        },
        {
            "id": 11,
            "image": "https://img-a.udemycdn.com/course/240x135/2634856_bdbf_2.jpg",
            "title": "Build Ecommerce Website to Master Django and Python",
            "author": "The Zero2Launch Team",
            "rating": 4.3,
            "hours": 23,
            "price": 9.99,
        },
        {
            "id": 12,
            "image": "https://img-a.udemycdn.com/course/240x135/1219332_bdd7.jpg",
            "title": "Artificial Intelligence A-Z™: Learn How To Build An AI",
            "author": "Kirill Eremenko",
            "rating": 4.3,
            "hours": 16,
            "price": 22.99,
        },
        {
            "id": 13,
            "image": "https://img-a.udemycdn.com/course/240x135/1153742_e649.jpg",
            "title": "Advanced AI: Deep Reinforcement Learning in Python",
            "author": "Lazy Programmer Team",
            "rating":4.6,
            "hours": 10,
            "price": 19.99,
        },
        {
            "id": 14,
            "image": "https://img-a.udemycdn.com/course/240x135/1754098_e0df_3.jpg",
            "title": "The Data Science Course 2020: Complete Data Science Bootcamp",
            "author": "Crazy Python Lover",
            "rating":4.7,
            "hours": 28,
            "price": 24.99,
        },
        {
            "id": 15,
            "image": "https://img-a.udemycdn.com/course/240x135/629302_8a2d_2.jpg",
            "title": "Learn Python Programming Masterclass",
            "author": "Crazy Python Lover",
            "rating": 4.5,
            "hours": 57,
            "price": 18.99,
        },
    ];

export default courses;